services:
  mysql:
    image: mysql/mysql-server:latest
    ports:
    - 3306:3306
    environment:
      MYSQL_DATABASE: kotlindb
      MYSQL_PASSWORD: root
      MYSQL_USERNAME: root
    container_name: mysql
    networks:
      - mysql-net
  aplicacao:
    image: lincolngadea/planetas
    ports:
    - 8080:8080
    environment:
      MYSQL_HOST: jdbc:mysql://mysql:3306/kotlindb
    depends_on:
      - mysql
    container_name: psw
    networks:
      - mysql-net
networks:
  mysql-net:
    driver: bridge
