spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kotlindb
    username: root
    password: root
    initialization-mode: always
  jpa:
    # colocar em false quando em produção
    show-sql: true
    hibernate:
      #colocar em none quando em produção
      ddl-auto: update
    generate-ddl: true
