spring:
  datasource:
    driverClassName: ${DRIVER_MYSQL:com.mysql.cj.jdbc.Driver}
    url: ${URL:jdbc:mysql://localhost:3306/kotlindb}
    username: ${USERNAME:root}
    password: root
    initialization-mode: always
  jpa:
    # colocar em false quando em produção
    show-sql: true
    hibernate:
      #colocar em none quando em produção
      ddl-auto: update
    generate-ddl: true
